name: Call jenkins-bridge
on:
  pull_request_target:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-pull/${{ github.event.number }}
  cancel-in-progress: true

jobs:
  check_job:
    uses: linuxdeepin/.github/.github/workflows/jenkins-bridge.yml@master
    secrets:
      BridgeToken: ${{ secrets.BridgeToken }}
